### ISSUE TITLE
Question shuffle order should be preserved for assessment questions

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Obojobo#123]
<a href="https://github.com/zachberry"><img src="https://avatars2.githubusercontent.com/u/73479?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zachberry](https://github.com/zachberry)**
_Thursday Mar 01, 2018 at 18:08 GMT_
_Originally opened as https://github.com/ucfcdl/Obojobo-Next/issues/125_

----

When showing assessment review we (currently) won't be able to display the answer choices for multiple choice questions in the same order as the student saw them. I don't consider this a deal breaker but we should be storing that data (both for being able to display exactly what a student saw as well as a research data point)

This will require shuffling questions on the server.

**Comment by iturgeon** [comment]
There may be a chance this was solved by the attempt state overhaul?

**Comment by zachberry** [comment]
I don't believe so - this is referring to the order of MCChoice items inside a Question and that data is still not kept even with the overhaul
