### ISSUE TITLE
9.1.0 Review: Clicking in the alt text input of Figure requires two clicks sometimes

### ISSUE THREAD

**Issue by zachberry** [ucfopen/Obojobo#1361]
You can see in the recording - Clicking in the alt text input focuses the input, then quickly unfocuses, requiring a second click. Seems like it may be related to #1360 ?

![2020-06-01 10 13 56](https://user-images.githubusercontent.com/73479/83417992-db99f500-a3f0-11ea-8984-cab9abae83fb.gif)

It seems after editing the alt text, closing the dialog, then reopening the dialog the alt text input works as expected. This bug only seems to popup when editing alt text after doing something else.

**Comment by vutoan1245** [comment]
Seems like it happens to all modals in the editor (Youtube, Iframe, ...)

**Comment by iturgeon** [comment]
is this addressed at all with #1369?

**Comment by vutoan1245** [comment]
@iturgeon 
Yes, it does fix it. But the issue still exists in the Youtube Modal.
I am looking deep into it to see the connection.
